instagram_accounts =  [{"username": "instagram", "description": "platform", "profession": "Social Media Platform", "country": "United States", "followers_millions": 686},
    {"username": "cristiano", "description": "footballer", "profession": "Footballer", "country": "Portugal", "followers_millions": 650},
    {"username": "leomessi", "description": "footballer", "profession": "Footballer", "country": "Argentina", "followers_millions": 504},
    {"username": "selenagomez", "description": "musician", "profession": "Musician and Actress", "country": "United States", "followers_millions": 421},
    {"username": "therock", "description": "actor", "profession": "Actor and Wrestler", "country": "United States", "followers_millions": 394},
    {"username": "kyliejenner", "description": "entrepreneur", "profession": "Media Personality", "country": "United States", "followers_millions": 394},
    {"username": "arianagrande", "description": "musician", "profession": "Musician and Actress", "country": "United States", "followers_millions": 376},
    {"username": "kimkardashian", "description": "entrepreneur", "profession": "Media Personality", "country": "United States", "followers_millions": 357},
    {"username": "beyonce", "description": "musician", "profession": "Musician and Actress", "country": "United States", "followers_millions": 312},
    {"username": "khloekardashian", "description": "entrepreneur", "profession": "Media Personality", "country": "United States", "followers_millions": 304},
    {"username": "nike", "description": "brand", "profession": "Sportswear Multinational", "country": "United States", "followers_millions": 301},
    {"username": "justinbieber", "description": "musician", "profession": "Musician", "country": "Canada", "followers_millions": 294},
    {"username": "kendalljenner", "description": "model", "profession": "Media Personality", "country": "United States", "followers_millions": 289},
    {"username": "taylorswift", "description": "musician", "profession": "Musician", "country": "United States", "followers_millions": 282},
    {"username": "natgeo", "description": "magazine", "profession": "Magazine", "country": "United States", "followers_millions": 279},
    {"username": "virat.kohli", "description": "cricketer", "profession": "Cricketer", "country": "India", "followers_millions": 270},
    {"username": "jlo", "description": "musician", "profession": "Musician and Actress", "country": "United States", "followers_millions": 249},
    {"username": "neymarjr", "description": "footballer", "profession": "Footballer", "country": "Brazil", "followers_millions": 229},
    {"username": "nickiminaj", "description": "musician", "profession": "Musician", "country": "Trinidad and Tobago", "followers_millions": 226},
    {"username": "kourtneykardash", "description": "entrepreneur", "profession": "Media Personality", "country": "United States", "followers_millions": 219},
    {"username": "mileycyrus", "description": "musician", "profession": "Musician and Actress", "country": "United States", "followers_millions": 213},
    {"username": "katyperry", "description": "musician", "profession": "Musician", "country": "United States", "followers_millions": 204},
    {"username": "zendaya", "description": "actress", "profession": "Actress and Singer", "country": "United States", "followers_millions": 180},
    {"username": "kevinhart4real", "description": "comedian", "profession": "Comedian and Actor", "country": "United States", "followers_millions": 177},
    {"username": "realmadrid", "description": "club", "profession": "Football Club", "country": "Spain", "followers_millions": 170},
    {"username": "iamcardib", "description": "musician", "profession": "Musician", "country": "United States", "followers_millions": 164},
    {"username": "kingjames", "description": "basketballer", "profession": "Basketball Player", "country": "United States", "followers_millions": 159},
    {"username": "ddlovato", "description": "musician", "profession": "Musician and Actress", "country": "United States", "followers_millions": 154},
    {"username": "badgalriri", "description": "entrepreneur", "profession": "Entrepreneur and Musician", "country": "Barbados", "followers_millions": 150},
    {"username": "champagnepapi", "description": "musician", "profession": "Musician and Rapper", "country": "Canada", "followers_millions": 143},
    {"username": "chrisbrownofficial", "description": "musician", "profession": "Musician", "country": "United States", "followers_millions": 144},
    {"username": "ellendegeneres", "description": "comedian", "profession": "Comedian and TV Host", "country": "United States", "followers_millions": 137},
    {"username": "fcbarcelona", "description": "club", "profession": "Football Club", "country": "Spain", "followers_millions": 133},
    {"username": "k.mbappe", "description": "footballer", "profession": "Footballer", "country": "France", "followers_millions": 122},
    {"username": "billieeilish", "description": "musician", "profession": "Musician", "country": "United States", "followers_millions": 121},
    {"username": "championsleague", "description": "competition", "profession": "Football Competition", "country": "Europe", "followers_millions": 118},
    {"username": "gal_gadot", "description": "actress", "profession": "Actress and Model", "country": "Israel", "followers_millions": 108},
    {"username": "shawnmendes", "description": "musician", "profession": "Musician", "country": "Canada", "followers_millions": 105},
    {"username": "gigi_hadid", "description": "model", "profession": "Model", "country": "United States", "followers_millions": 104},
    {"username": "nasa", "description": "space", "profession": "Space Agency", "country": "United States", "followers_millions": 100},
    {"username": "priyankachopra", "description": "actress", "profession": "Actress and Singer", "country": "India", "followers_millions": 99},
    {"username": "snoopdogg", "description": "musician", "profession": "Musician", "country": "United States", "followers_millions": 97},
    {"username": "avicii", "description": "musician", "profession": "DJ & Producer", "country": "Sweden", "followers_millions": 96},
    {"username": "davidbeckham", "description": "footballer", "profession": "Former Footballer", "country": "United Kingdom", "followers_millions": 95},
    {"username": "dualipa", "description": "musician", "profession": "Musician", "country": "United Kingdom", "followers_millions": 93},
    {"username": "vindiesel", "description": "actor", "profession": "Actor", "country": "United States", "followers_millions": 92},
    {"username": "emmawatson", "description": "actress", "profession": "Actress", "country": "United Kingdom", "followers_millions": 91},
    {"username": "karimbenzema", "description": "footballer", "profession": "Footballer", "country": "France", "followers_millions": 90},
    {"username": "shakira", "description": "musician", "profession": "Musician", "country": "Colombia", "followers_millions": 89},
    {"username": "louisvuitton", "description": "brand", "profession": "Luxury Fashion", "country": "France", "followers_millions": 88},
    {"username": "willsmith", "description": "actor", "profession": "Actor and Producer", "country": "United States", "followers_millions": 87},
    {"username": "charlidamelio", "description": "influencer", "profession": "Social Media Influencer", "country": "United States", "followers_millions": 86},
    {"username": "nba", "description": "sports", "profession": "Basketball League", "country": "United States", "followers_millions": 85},
    {"username": "harrystyles", "description": "musician", "profession": "Musician", "country": "United Kingdom", "followers_millions": 84},
    {"username": "badbunnypr", "description": "musician", "profession": "Musician", "country": "Puerto Rico", "followers_millions": 83},
    {"username": "zayn", "description": "musician", "profession": "Musician", "country": "United Kingdom", "followers_millions": 82},
    {"username": "rihanna", "description": "musician", "profession": "Musician & Entrepreneur", "country": "Barbados", "followers_millions": 81},
    {"username": "brunomars", "description": "musician", "profession": "Musician", "country": "United States", "followers_millions": 80},
    {"username": "theweeknd", "description": "musician", "profession": "Musician", "country": "Canada", "followers_millions": 79},
    {"username": "tomholland2013", "description": "actor", "profession": "Actor", "country": "United Kingdom", "followers_millions": 78},
    {"username": "marvel", "description": "entertainment", "profession": "Entertainment Brand", "country": "United States", "followers_millions": 77},
    {"username": "lukamodric10", "description": "footballer", "profession": "Footballer", "country": "Croatia", "followers_millions": 76},
    {"username": "djkhaled", "description": "musician", "profession": "DJ & Producer", "country": "United States", "followers_millions": 75},
    {"username": "paulpogba", "description": "footballer", "profession": "Footballer", "country": "France", "followers_millions": 74},
    {"username": "sachintendulkar", "description": "cricketer", "profession": "Cricketer", "country": "India", "followers_millions": 73},
    {"username": "championsleague", "description": "sports", "profession": "Football Competition", "country": "Europe", "followers_millions": 72},
    {"username": "elonmusk", "description": "entrepreneur", "profession": "Business Magnate", "country": "United States", "followers_millions": 71},
    {"username": "narendramodi", "description": "politician", "profession": "Prime Minister", "country": "India", "followers_millions": 70},
    {"username": "usainbolt", "description": "athlete", "profession": "Athlete", "country": "Jamaica", "followers_millions": 69},
    {"username": "goldenretrievers", "description": "pets", "profession": "Animal Influencer", "country": "United States", "followers_millions": 68},
    {"username": "joebiden", "description": "politician", "profession": "President of the USA", "country": "United States", "followers_millions": 67},
    {"username": "kanyewest", "description": "musician", "profession": "Musician & Entrepreneur", "country": "United States", "followers_millions": 66},
    {"username": "samsmith", "description": "musician", "profession": "Musician", "country": "United Kingdom", "followers_millions": 65},
    {"username": "ed_sheeran", "description": "musician", "profession": "Musician", "country": "United Kingdom", "followers_millions": 64},
    {"username": "serenawilliams", "description": "athlete", "profession": "Tennis Player", "country": "United States", "followers_millions": 63},
    {"username": "nikkietutorials", "description": "influencer", "profession": "Beauty Influencer", "country": "Netherlands", "followers_millions": 62},
    {"username": "markiplier", "description": "youtuber", "profession": "YouTuber", "country": "United States", "followers_millions": 61},
    {"username": "pewdiepie", "description": "youtuber", "profession": "YouTuber", "country": "Sweden", "followers_millions": 60},
]
